### PR TITLE
Revert "Chrysler branch"

### PR DESCRIPTION
**Pull request by plaidUp**
Reverts plaidUp/Workspace#1

### CODE REVIEW

**Review by Alex-Chrysler — DISMISSED** [review]
What a good looking branch. Keep it up! Proud of you!

**Comment by bitze003** [comment]
I'm a bit worried about this code.

**Comment by bitze003** [comment]
I am only approving because I was told to do so.

**Comment by chrisfrederick** [comment]
This is the worst code in the history of things

**Comment by Alex-Mastin** [comment]
This is that good good

**Review by Alex-Chrysler — APPROVED** [review]
Sure

**Comment by chrisfrederick** [comment]
no no no

**Pull request merged**
